name: Autolabel
on:
  # Run manually
  workflow_dispatch:
  # # Run daily
  # schedule:
  #   - cron: "0 0 * * *" # https://crontab.guru/daily
  # # Run when issues are created
  # issues:
  #   types: [opened]

jobs:
  wcag_labeler:
    name: WCAG Labeler
    runs-on: ubuntu-latest
    steps:
      - uses: smockle/action-autolabel@dist
        with:
          search_objects: '[{ "text": "4.1.1", "label": "WCAG 4.1.1" }, { "text": "4.1.2", "label": "4.1.2" }]'
          limit_matches: false
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
