name: Test
on: pull_request

jobs:
  test:
    name: Test
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: "https://registry.npmjs.org"
      - run: npm i -g npm@7 --registry=https://registry.npmjs.org && npm --version
      - run: npm ci
      - run: npm run test:unit
      - uses: codecov/codecov-action@v2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
